logging:
  level.root: info

  #Data Source
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
  #JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    properties.hibernate.default_schema: teai8_2
    show-sql: true
